#!/bin/sh

if [[ -f '/data/.evcc_disabled' ]] ; then
    echo "*** evcc is disabled, not starting ***"
    svc -d /service/evcc*
    exit 0
fi

echo "*** starting evcc ***"

until netstat -an | grep 0.0.0.0:1883.*LISTEN > /dev/null; do
    echo "waiting for MQTT broker to start ..."
    sleep 1
done

# create config file
/data/evcc/evcc-autoconfig.py

exec 2>&1
exec /data/evcc/evcc -c /data/evcc/evcc.ve.yaml