#!/bin/sh

VERSION="$(head -n 1 /opt/victronenergy/version | tr -d 'v')"

MAJOR=`echo $VERSION | cut -d. -f1`
MINOR=`echo $VERSION | cut -d. -f2 | cut -d~ -f1`

# controlling evcc service via dbus available from v3.30~5
if [[ $MAJOR -lt 3 ]]; then
    exit 1
elif [[ $MAJOR -gt 3 ]]; then
    exit 0
else
    if [[ $MINOR -lt 30 ]]; then
        exit 1
    elif [[ $MINOR -gt 30 ]]; then
        exit 0
    elif [[ $VERSION =~ "~" ]]; then
        BUILD=`echo $VERSION | cut -d. -f2 | cut -d~ -f2`
        if [[ $BUILD -lt 5 ]]; then
            exit 1
        else
            exit 0
        fi
    else
        exit 0
    fi
fi